### ISSUE TITLE
Migration to version 10.0-website_blog_rss

### ISSUE THREAD

**Issue by gfcapalbo** [gfcapalbo/addons-vauxoo#1]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0-website_blog_rss

# Modules to migrate

- [ ] account_amortization
- [ ] account_analytic_required
- [ ] account_anglo_saxon_missing_key
- [ ] account_anglo_saxon_stock_move
- [ ] account_anglo_saxon_stock_move_purchase
- [ ] account_anglo_saxon_stock_move_sale
- [ ] account_asset_analytic
- [ ] account_asset_date
- [ ] account_asset_move_check
- [ ] account_bank_statement_unfucked
- [ ] account_bank_statement_vauxoo
- [ ] account_budget_imp
- [ ] account_chart_wiz_dates
- [ ] account_closure_preparation
- [ ] account_currency_tools
- [ ] account_entries_report_group_by_ref
- [ ] account_group_auditory
- [ ] account_group_auditory_assets
- [ ] account_invoice_line_asset_category_required
- [ ] account_invoice_line_currency
- [ ] account_invoice_number
- [ ] account_invoice_regular_validation
- [ ] account_invoice_show_by_user
- [ ] account_invoice_supplier_quantity_attachments
- [ ] account_invoice_tax
- [ ] account_ledger_report
- [ ] account_move_cancel
- [ ] account_move_filters
- [ ] account_move_folio
- [ ] account_move_group
- [ ] account_move_line_address
- [ ] account_move_line_base_tax
- [ ] account_move_line_dp_product
- [ ] account_move_line_extended
- [ ] account_move_line_group_analytic
- [ ] account_move_line_group_by_asset
- [ ] account_move_line_group_by_extend
- [ ] account_move_line_grouping
- [ ] account_move_line_production
- [ ] account_move_nonzero
- [ ] account_move_report
- [ ] account_move_sum_all_credits_debits
- [ ] account_move_validate_multi_wizard
- [ ] account_name_ref_search
- [ ] account_order_wizard
- [ ] account_payment_approve_invoice
- [ ] account_reconcile_advance
- [ ] account_reconcile_advance_tax
- [ ] account_reconcile_grouping
- [ ] account_reconcile_search
- [ ] account_refund_early_payment
- [ ] account_relation_move
- [ ] account_remove_account_move_amount_field
- [ ] account_report_general_ledger_no_journal
- [ ] account_smart_unreconcile
- [ ] account_tax_importation
- [ ] account_update_amount_tax_in_move_lines
- [ ] account_voucher_category
- [ ] account_voucher_department
- [ ] account_voucher_draft
- [ ] account_voucher_move_id
- [ ] account_voucher_no_check_default
- [ ] account_voucher_requester
- [ ] account_voucher_tax
- [ ] account_voucher_tax_sat
- [ ] account_wizard_vouchers_invoice
- [ ] active_journal_period
- [ ] aging_due_report
- [ ] analytic_entry_line_group
- [ ] analytic_entry_line_journal
- [ ] analytic_entry_line_move
- [ ] analytic_entry_line_partner
- [ ] analytic_entry_line_period
- [ ] analytic_entry_line_plans
- [ ] analytic_entry_line_taxcode
- [ ] analytic_plans_group
- [ ] analytic_split_quantity
- [ ] bank_iva_report
- [ ] baremo
- [ ] base_user_signature_logo
- [ ] base_vat_country
- [ ] base_vat_principal_view
- [ ] bom_inventory_information
- [ ] change_invoice_number
- [ ] clean_user_groups
- [ ] commission_payment
- [ ] company_description
- [ ] configure_account_partner
- [ ] configure_chart_account
- [ ] controller_report_xls
- [ ] costing_method_settings
- [ ] crm_claim_summary_report
- [ ] crm_cost_issue
- [ ] crm_profile_reporting
- [ ] debit_credit_note
- [ ] decimal_precision_currency
- [ ] decimal_precision_tax
- [ ] default_warehouse_from_sale_team
- [ ] deliver_project
- [ ] email_template_att_dinamic
- [ ] email_template_comment
- [ ] expired_task_information
- [ ] forward_mail
- [ ] group_button_wkf_send_rfq
- [ ] group_configurations_account
- [ ] hr_childrens
- [ ] hr_expense_analytic
- [ ] hr_expense_replenishment
- [ ] hr_expense_replenishment_cancel
- [ ] hr_expense_replenishment_tax
- [ ] hr_job_positions_extended
- [ ] hr_lastname
- [ ] hr_payroll_cancel
- [ ] hr_payroll_multicompany
- [ ] hr_payslip_paid
- [ ] hr_payslip_validation_home_address
- [ ] hr_salesman_commission
- [ ] hr_timesheet_reports
- [ ] import_tax_tariff
- [ ] inactive_account_children
- [ ] incoterm_delivery_type
- [ ] incoterm_ext
- [ ] inventory_stock_report
- [ ] invisible_aml_tax
- [ ] invoice_cancel_islr
- [ ] invoice_cancel_iva
- [ ] invoice_comment_view_tree
- [ ] invoice_commission
- [ ] invoice_date_ref
- [ ] invoice_datetime
- [ ] invoice_discount
- [ ] invoice_double_validation
- [ ] invoice_multicompany_report
- [ ] invoice_number_view_tree
- [ ] invoice_print_multicompany
- [ ] invoice_report_multicompany
- [ ] invoice_report_per_journal
- [ ] invoice_sale_ref
- [ ] invoice_so
- [ ] ir_actions_report_xml_multicompany
- [ ] ir_ui_view_filter_arch
- [ ] issue_view
- [ ] mail_add_followers_multirecord
- [ ] merge_editing
- [ ] message_post_model
- [ ] message_post_test
- [ ] mrp_bom_constraint
- [ ] mrp_bom_standard_price
- [ ] mrp_bom_subproduct_cost
- [ ] mrp_button_box
- [ ] mrp_location_line_production
- [ ] mrp_location_route
- [ ] mrp_partial_production
- [ ] mrp_product_capacity
- [ ] mrp_production_analytic_acc
- [ ] mrp_production_bom_related
- [ ] mrp_production_filter_date
- [ ] mrp_production_filter_product
- [ ] mrp_production_procurement_order
- [ ] mrp_production_security_force
- [ ] mrp_pt_planified
- [ ] mrp_routing_account_journal
- [ ] mrp_scheduled_onchange_product
- [ ] mrp_subproduct_pt_planified
- [ ] mrp_subproduction
- [ ] mrp_webkit_report_wizard
- [ ] mrp_workcenter_account_move
- [ ] mrp_workcenter_management
- [ ] mrp_workcenter_responsible
- [ ] mrp_workcenter_segmentation
- [ ] mrp_workorder_variation
- [ ] note_to_task
- [ ] partner_credit_limit
- [ ] partner_effective_sale
- [ ] partner_foreign
- [ ] partner_invoice_description
- [ ] partner_notification_advance
- [ ] partner_products
- [ ] partner_property_accounts
- [ ] partner_ref_search
- [ ] partner_required_in_acc_move_line
- [ ] partner_search_by_vat
- [ ] partner_validate_vat
- [ ] payment_term_type
- [ ] payroll_amount_residual
- [ ] periodic_inventory_valuation
- [ ] picking_force_availability
- [ ] picking_from_invoice
- [ ] picking_verification_report
- [ ] point_of_sale_by_month
- [ ] point_of_sale_reprint_tree
- [ ] portal_project_kanban_fields
- [ ] pos_calculator
- [ ] pos_delivery_restaurant
- [ ] pos_product_filter
- [ ] pr_line_related_po_line
- [ ] procurement_cancel
- [ ] procurement_so2po_shiping_address
- [ ] product_attr_description
- [ ] product_categ_name_untranslated
- [ ] product_category_attributes
- [ ] product_category_multicompany
- [ ] product_context_date
- [ ] product_cost_usd
- [ ] product_customer_code
- [ ] product_customs_rate
- [ ] product_do_merge
- [ ] product_extended_segmentation
- [ ] product_extended_variants
- [ ] product_historical_price
- [ ] product_images_olbs
- [ ] product_lifecycle
- [ ] product_model_no
- [ ] product_name_untranslated
- [ ] product_price_visible
- [ ] product_pricelist_date
- [ ] product_pricelist_report_qweb
- [ ] product_product_multi_link
- [ ] product_properties_by_category
- [ ] product_rfq
- [ ] product_unique_default_code
- [ ] product_uom_update
- [ ] production_lot_group_by_name
- [ ] products_finished_scrap
- [ ] project_complete_name
- [ ] project_contract_validations
- [ ] project_followers_rule
- [ ] project_image
- [ ] project_issue_fix_progress
- [ ] project_issue_management
- [ ] project_issue_report
- [ ] project_issue_report2
- [ ] project_search_create_uid
- [ ] project_task_work
- [ ] purchase_changeless_move_lines
- [ ] purchase_discount
- [ ] purchase_incoming_qty
- [ ] purchase_multi_report
- [ ] purchase_order_cancel
- [ ] purchase_order_contract_analyst
- [ ] purchase_order_department
- [ ] purchase_order_description
- [ ] purchase_order_line_quantity
- [ ] purchase_order_line_sequence
- [ ] purchase_order_requisitor
- [ ] purchase_order_type
- [ ] purchase_requisition_contract_analyst
- [ ] purchase_requisition_currency
- [ ] purchase_requisition_department
- [ ] purchase_requisition_for_everybody
- [ ] purchase_requisition_incoterms
- [ ] purchase_requisition_line_analytic
- [ ] purchase_requisition_line_description
- [ ] purchase_requisition_line_plan
- [ ] purchase_requisition_line_price_unit
- [ ] purchase_requisition_line_uom_check
- [ ] purchase_requisition_line_view
- [ ] purchase_requisition_priority
- [ ] purchase_requisition_remarks
- [ ] purchase_requisition_supplier_list
- [ ] purchase_requisition_type
- [ ] purchase_supplier
- [ ] purchase_test_data_imp
- [ ] purchase_third_validation
- [ ] purchase_user_validation
- [ ] recovery_attachments_bd
- [ ] report_move_voucher
- [ ] report_multicompany
- [ ] report_parser_html
- [ ] report_process_production
- [ ] res_bank_menu_payroll
- [ ] res_partner_btree
- [ ] sale_block_cancellation
- [ ] sale_date_confirm
- [ ] sale_double_validation
- [ ] sale_line_import
- [ ] sale_margin_commision
- [ ] sale_margin_percentage
- [ ] sale_order_copy_line
- [ ] sale_order_create_task_planned_hours
- [ ] sale_order_customized
- [ ] sale_order_dates_max
- [ ] sale_order_line_quantity
- [ ] sale_test_data_imp
- [ ] sale_uncommitted_product
- [ ] sale_uom_group
- [ ] sale_website_cleanup
- [ ] send_author_mail
- [ ] send_mail_task
- [ ] set_group_by_department
- [ ] split_invoice_button
- [ ] sprint_kanban
- [ ] standard_price_acl
- [ ] stock_accrual_report
- [ ] stock_allow_past_date
- [ ] stock_card
- [ ] stock_card_segmentation
- [ ] stock_deviation_account
- [ ] stock_easy_internal_transfer
- [ ] stock_hide_set_zero_button
- [ ] stock_inventory_delete
- [ ] stock_invoice_state_editable
- [ ] stock_landed_costs_average
- [ ] stock_landed_costs_segmentation
- [ ] stock_location_acml
- [ ] stock_location_code
- [ ] stock_move_entries
- [ ] stock_move_name
- [ ] stock_move_tracking_number
- [ ] stock_picking_invoice_validation
- [ ] stock_picking_log_message_transfer
- [ ] stock_picking_security_force
- [ ] stock_picking_show_entries_info
- [ ] stock_picking_validate_past
- [ ] stock_purchase_analytic_plans
- [ ] stock_purchase_check_fulfillment
- [ ] stock_purchase_expiry
- [ ] stock_purchase_requisitor
- [ ] stock_purchase_type
- [ ] stock_quant_cost_segmentation
- [ ] stock_quant_menu
- [ ] stock_sale_invoice_line
- [ ] stock_sale_order_line
- [ ] stock_transfer_avoid_lot_repeated_split
- [ ] stock_unfuck
- [ ] stock_view_product
- [ ] supplier_invoice_number_unique
- [ ] sync_youtube
- [ ] test_sale_team_warehouse
- [ ] transaction_type
- [ ] update_period
- [ ] user_wzd
- [ ] validate_stock_move_product
- [ ] validate_stock_picking
- [ ] validate_type_line_invoice
- [ ] website_authorized_service_centers
- [x] website_blog_rss
- [ ] website_comment_approval
- [ ] website_customer_also_purchased
- [ ] website_hr_social_icons
- [ ] website_order_confirm
- [ ] website_product_availability
- [ ] website_product_comment_purchased
- [ ] website_product_manufacturer_url
- [ ] website_product_rss
- [ ] website_rate_product
- [ ] website_variants_extra
